# Generated by Django 5.0 on 2024-09-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 48, 48, 497468))),
                ('data_fim', models.DateTimeField()),
                ('peso', models.IntegerField(max_length=10)),
            ],
        ),
    ]
