# Generated by Django 5.0 on 2024-09-22 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 8, 694701)),
        ),
    ]
