# Generated by Django 5.0 on 2024-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_data_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_ini',
            field=models.DateTimeField(),
        ),
    ]
