# Generated by Django 5.0 on 2024-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_nome_alter_agenda_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(default='agenda-2024-09-22 14:17:11.891082', max_length=200),
        ),
    ]
