# Generated by Django 5.1.1 on 2024-09-25 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_status_alter_agenda_nome_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(default='agenda-2024-09-25 00:01:58.764490', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agenda.agenda'),
        ),
    ]
